### PR TITLE
[SBT-Warnings] Turn up and fix compiler warnings

### PR DESCRIPTION
**Pull request by c-harding**
This commit turns up the level of warnings, and then resolves the outstanding warnings

### CODE REVIEW

**Comment by c-harding** [comment]
Is it possible to add a check that there are no warnings to the CI?

**Comment by c-harding** [comment]
Hope that code coverage is good enough for you guys

**Comment by jaylees14** [comment]
@xsanda We could add a CI build step that uses the `-Xfatal-warnings` flag, but is non blocking. Might be worth doing this as part of the migration to travis?

**Review by jaylees14 — APPROVED** [review]
Nice one, thanks @xsanda 👍

**Review by Lewiky — APPROVED** [review]
LGTM

**Pull request merged**
