### PR TITLE
[Testing] [Go-gen] Fix illegal shadowing of ID in test

### PR DESCRIPTION
**Pull request by c-harding**
For some reason `id` was being shadowed as an int, which was leading to some illegal SQL statements being generated.

### CODE REVIEW

**Review by jaylees14 — APPROVED** [review]
Cool. Although this test is technically valid, given the input it did provide correct output. It's just that the ID field was assumed to be the primary key.

This was also done way before we had the concept of `IDAttribute`, or even `UUID` primary keys.

**Comment by c-harding** [comment]
@jaylees14 I thought that would have been the case, but I was updating it for structs and thought I may as well update it here too. Tests are often where people look to understand how our stuff works

**Comment by jaylees14** [comment]
> @jaylees14 I thought that would have been the case, but I was updating it for structs and thought I may as well update it here too. Tests are often where people look to understand how our stuff works

Absolutely - wasn't a dig at all, just thought I'd give some context - thanks for fixing 😄

**Review by Lewiky — APPROVED** [review]
Cool, nice job

**Pull request merged**
