### PR TITLE
[example] Add ImageServer example

### PR DESCRIPTION
**Pull request by c-harding**
This is going to break because an attribute (of type data or date/time) having the same name as its class will result in a name clash (source: https://github.com/TempleEight/temple/blob/develop/src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala#L90). I’d be interested in people’s solutions to this: ban all attributes from having the same name as their services, rename the new struct in the create block from `image` to `newImage`, or ban specifically this case?

I raise this because the Deliveroo example has the equivalent of this in a struct, which my generation has raised.

Update: now naming an attribute the same as its block is a validation error. This triggered a naming error in the simple.temple, which has been updated at the cost of many lines.

Also spotted was another issue based on the original incorrect assumption: attributes may not be named the same as imports etc, as they are sometimes rendered as local variables. This has been fixed too, with the changes to NameClashes

_Previous solution: rename the parent in the case of a clash. This means the service is now called ImageServerImage, and the attribute remains as before._ (issue: the API should not change that much when children are added.)

### CODE REVIEW

**Comment by jaylees14** [comment]
If we rename the variable in the Go code, we’re still going to have to ban that new name from occurring in the attributes, so I’d be tempted to say the quickest fix is banning attributes with the same name as the service.

**Comment by c-harding** [comment]
actually, tempted to go with Jay’s solution even though it does interfere more with the user’s workflow: this will make regen more awkward when such an attribute is added, as the whole project is moved. Alternatively, could rename the attr?

TODO: also check that the current approach happens after the attr has been renamed

**Comment by Lewiky** [comment]
I think going with Jay's solution here will be fine, The user is like 3 people and I feel like this level of detail isn't going to bother them. Not like this is going out to millions

**Comment by c-harding** [comment]
@jaylees14 this is going to get messy: simple.temple has `User: service { user: string; ... }`

**Review by jaylees14 — APPROVED** [review]
Cool

**Review by Lewiky — APPROVED** [review]
coolio

**Comment by c-harding** [comment]
Update: now naming an attribute the same as its block is a validation error. This triggered a naming error in the simple.temple, which has been updated at the cost of many lines.

Also spotted was another issue based on the original incorrect assumption: attributes may not be named the same as imports etc, as they are sometimes rendered as local variables. This has been fixed too, with the changes to NameClashes

**Pull request merged**
