### PR TITLE
[fmt] Format multiline strings correctly

### PR DESCRIPTION
**Pull request by jaylees14**
It seems I have an inability to write multiline strings correctly. So - it seems only right to blame the tools and make the formatter do it for me 😄 

See https://scalameta.org/scalafmt/docs/configuration.html#assumestandardlibrarystripmargin for ref

### CODE REVIEW

**Comment by willjvsmith** [comment]
This been run over the whole repo?

**Comment by jaylees14** [comment]
> This been run over the whole repo?

According to IntelliJ, yep, everything in `src`

**Review by willjvsmith — APPROVED** [review]
Good stuff

**Review by Lewiky — APPROVED** [review]
LGTM

**Pull request merged**
