### PR TITLE
[OpenAPI-gen] Lift parameters up a level as per spec changes

### PR DESCRIPTION
**Pull request by c-harding**
This runs on top of #136, diff will then shrink

Edit: it’s shrunk

### CODE REVIEW

**Review by jaylees14 — APPROVED** [review]

**Review by willjvsmith — APPROVED** [review]
Good stuff

**Review by Lewiky — APPROVED** [review]
LGTM

**Comment by willjvsmith** [comment]
PARCE QUE C'EST NE PAS MERGÉ

**Pull request merged**
